services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: wedding-laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ..:/var/www
    depends_on:
      - db
      - redis
    networks:
      - wedding-network

  nginx:
    image: nginx:latest
    container_name: wedding-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ..:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - wedding-network

  db:
    image: postgres:latest
    container_name: wedding-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wedding_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - wedding-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: wedding-redis
    restart: unless-stopped
    networks:
      - wedding-network

  mailhog:
    image: mailhog/mailhog
    container_name: wedding-mailhog
    ports:
      - "8025:8025"
    networks:
      - wedding-network

networks:
  wedding-network:

volumes:
  pgdata: